M48
; DRILL file {KiCad 9.0.0} date 2025-04-02T18:41:46+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-02T18:41:46+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.700
%
G90
G05
T1
X144.91Y-76.7
X150.69Y-76.7
T2
X122.2Y-119.2
X181.7Y-73.0
M30
